Repository flairNLP/fundus, pull requests merged in 2024-05, with the labels that each got.

#432 added zdf.de
  docs/supported_publishers.md
  src/fundus/publishers/de/__init__.py
  src/fundus/publishers/de/zdf.py
  tests/resources/parser/test_data/de/ZDF.json
  tests/resources/parser/test_data/de/ZDF_2024_04_22.html.gz
  tests/resources/parser/test_data/de/meta.info
Labels: good first PR

#517 Remove previous file when using `-o` option in test case script
  scripts/generate_parser_test_files.py
  tests/utility.py
Labels: enhancement

#519 Set PYTHONPATH to the Root of the Repository for the Publisher Coverage Actions
  .github/workflows/publisher_coverage.yaml
Labels: bug
