Repository flairNLP/fundus, pull requests merged in 2024-04, with the labels that each got.

#408 Add custom filter for `publisher_coverage` to skip boolean values
  scripts/publisher_coverage.py
Labels: bug fix

#338 Add `body` to unit tests
  scripts/generate_parser_test_files.py
  src/fundus/parser/data.py
  src/fundus/publishers/de/waz.py
  src/fundus/publishers/us/business_insider.py
  tests/resources/parser/test_data/at/ORF.json
  tests/resources/parser/test_data/ch/SRF.json
  tests/resources/parser/test_data/de/BSZ.json
  tests/resources/parser/test_data/de/BerlinerZeitung.json
  tests/resources/parser/test_data/de/Bild.json
  tests/resources/parser/test_data/de/BusinessInsiderDE.json
  tests/resources/parser/test_data/de/DW.json
  tests/resources/parser/test_data/de/DieWelt.json
  tests/resources/parser/test_data/de/DieZeit.json
  tests/resources/parser/test_data/de/FAZ.json
  tests/resources/parser/test_data/de/Focus.json
  tests/resources/parser/test_data/de/MDR.json
  tests/resources/parser/test_data/de/Merkur.json
  tests/resources/parser/test_data/de/NDR.json
  tests/resources/parser/test_data/de/NTV.json
  tests/resources/parser/test_data/de/SZ.json
  tests/resources/parser/test_data/de/SpiegelOnline.json
  tests/resources/parser/test_data/de/Stern.json
  tests/resources/parser/test_data/de/Tagesschau.json
  tests/resources/parser/test_data/de/Taz.json
  tests/resources/parser/test_data/de/WAZ.json
  tests/resources/parser/test_data/fr/LeMonde.json
  tests/resources/parser/test_data/lt/LRT.json
  tests/resources/parser/test_data/na/TheNamibian.json
  tests/resources/parser/test_data/uk/TheGuardian.json
  tests/resources/parser/test_data/uk/TheIndependent.json
  tests/resources/parser/test_data/uk/TheTelegraph.json
  tests/resources/parser/test_data/uk/iNews.json
  tests/resources/parser/test_data/us/APNews.json
  tests/resources/parser/test_data/us/BusinessInsider.json
  tests/resources/parser/test_data/us/CNBC.json
  tests/resources/parser/test_data/us/FoxNews.json
  tests/resources/parser/test_data/us/FreeBeacon.json
  tests/resources/parser/test_data/us/LATimes.json
  tests/resources/parser/test_data/us/OccupyDemocrats.json
  tests/resources/parser/test_data/us/Reuters.json
  tests/resources/parser/test_data/us/TheGatewayPundit.json
  tests/resources/parser/test_data/us/TheIntercept.json
  tests/resources/parser/test_data/us/TheNation.json
  tests/resources/parser/test_data/us/TheNewYorker.json
  tests/resources/parser/test_data/us/WashingtonTimes.json
  tests/resources/parser/test_data/us/WorldTruth.json
  tests/test_parser.py
  tests/utility.py
Labels: enhancement

#423 Rework `ExtractionFilter` to adept to boolean values
  scripts/generate_parser_test_files.py
  scripts/publisher_coverage.py
  src/fundus/scraping/filter.py
  tests/test_filter.py
Labels: DON'T MERGE, rework

#361 Implement module scoped logging
  scripts/generate_parser_test_files.py
  src/fundus/logging.py
  src/fundus/logging/__init__.py
  src/fundus/logging/logger.py
  src/fundus/scraping/article.py
  src/fundus/scraping/crawler.py
  src/fundus/scraping/html.py
  src/fundus/scraping/scraper.py
  src/fundus/scraping/session.py
  src/fundus/scraping/url.py
Labels: enhancement

#450 gh446: predict encodings for responses
  src/fundus/scraping/html.py
Labels: enhancement

#454 Use `!r` instead of single quotes for strings in f-strings
  src/fundus/parser/base_parser.py
  src/fundus/parser/data.py
  src/fundus/publishers/base_objects.py
  src/fundus/scraping/article.py
  src/fundus/scraping/html.py
  src/fundus/scraping/scraper.py
  src/fundus/scraping/url.py
  tests/test_parser.py
  tests/utility.py
Labels: enhancement

#459 Fix URL Filter Bug
  src/fundus/scraping/scraper.py
Labels: bug fix
